# [[ Tests ]]
# [[ ----------------------------------------------------------------------- ]]
# [[ ----------------------------------------------------------------------- ]]

add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/test_containers")
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/test_utilities")
add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/test_database")

# Add more tests as needed...

# [[ ----------------------------------------------------------------------- ]]
# [[ ----------------------------------------------------------------------- ]]
# [[ Tests ]]
